from PyQt5.QtGui import QPixmap, QPainter
from PyQt5.QtWidgets import QWidget ,QMessageBox,QApplication,QStackedWidget ,QVBoxLayout,QHBoxLayout,QListWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, pyqtSignal, QTimer,QDate, QTime
import os
from datetime import datetime
import pytz
import kfcCombine
import viewMenu_Mac_MaL_SuB


class ViewMenus_Mac_Mal_Sub_C(QWidget):

	def setup_Ui_Pm_Mcdonalds(self):
		self.setObjectName('PM Mcdonald')
		self.resize(800,600)
		self.setWindowOpacity(0.9)

		self.setAutoFillBackground(True)
		p = self.palette()
		p.setColor(self.backgroundRole(), QtCore.Qt.black)
		self.setPalette(p)
		self.gridLayout = QtWidgets.QGridLayout(self)
		self.gridLayout.setObjectName('gridLayout')



		self.item_six_price = QtWidgets.QLabel(self)
		self.item_six_price.setGeometry(QtCore.QRect(280, 310, 31, 16))
		self.item_six_price.setObjectName("item_six_price")
		self.item_seven_pic = QtWidgets.QLabel(self)
		self.item_seven_pic.setGeometry(QtCore.QRect(450, 229, 100, 71))
		self.item_seven_pic.setText("")
		self.item_seven_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Nugguts.png"))
		self.item_seven_pic.setScaledContents(True)
		self.item_seven_pic.setObjectName("item_seven_pic")
		self.item_eight_pic = QtWidgets.QLabel(self)
		self.item_eight_pic.setGeometry(QtCore.QRect(660, 219, 91, 81))
		self.item_eight_pic.setText("")
		self.item_eight_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Coke.png"))
		self.item_eight_pic.setScaledContents(True)
		self.item_eight_pic.setObjectName("item_eight_pic")
		self.item_eight_text = QtWidgets.QLabel(self)
		self.item_eight_text.setGeometry(QtCore.QRect(650, 290, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_eight_text.setFont(font)
		self.item_eight_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_eight_text.setObjectName("item_eight_text")
		self.item_five_price = QtWidgets.QLabel(self)
		self.item_five_price.setGeometry(QtCore.QRect(70, 310, 31, 16))
		self.item_five_price.setObjectName("item_five_price")
		self.item_six_text = QtWidgets.QLabel(self)
		self.item_six_text.setGeometry(QtCore.QRect(250, 290, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_six_text.setFont(font)
		self.item_six_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_six_text.setObjectName("item_six_text")
		self.item_seven_price = QtWidgets.QLabel(self)
		self.item_seven_price.setGeometry(QtCore.QRect(480, 310, 31, 16))
		self.item_seven_price.setObjectName("item_seven_price")
		self.item_five_pic = QtWidgets.QLabel(self)
		self.item_five_pic.setGeometry(QtCore.QRect(50, 220, 91, 71))
		self.item_five_pic.setText("")
		self.item_five_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Chicken.png"))
		self.item_five_pic.setScaledContents(True)
		self.item_five_pic.setObjectName("item_five_pic")
		self.item_five_text = QtWidgets.QLabel(self)
		self.item_five_text.setGeometry(QtCore.QRect(40, 290, 111, 20))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_five_text.setFont(font)
		self.item_five_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_five_text.setObjectName("item_five_text")
		self.item_seven_text = QtWidgets.QLabel(self)
		self.item_seven_text.setGeometry(QtCore.QRect(440, 290, 141, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_seven_text.setFont(font)
		self.item_seven_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_seven_text.setObjectName("item_seven_text")
		self.item_six_pic = QtWidgets.QLabel(self)
		self.item_six_pic.setGeometry(QtCore.QRect(260, 190, 100, 100))
		self.item_six_pic.setText("")
		self.item_six_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Wrap.png"))
		self.item_six_pic.setScaledContents(True)
		self.item_six_pic.setObjectName("item_six_pic")
		self.item_eight_price = QtWidgets.QLabel(self)
		self.item_eight_price.setGeometry(QtCore.QRect(690, 310, 31, 16))
		self.item_eight_price.setObjectName("item_eight_price")
		self.item_two_price = QtWidgets.QLabel(self)
		self.item_two_price.setGeometry(QtCore.QRect(280, 130, 31, 16))
		self.item_two_price.setObjectName("item_two_price")
		self.item_three_pic = QtWidgets.QLabel(self)
		self.item_three_pic.setGeometry(QtCore.QRect(450, 20, 100, 100))
		self.item_three_pic.setText("")
		self.item_three_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Double Cheese Burger.png"))
		self.item_three_pic.setScaledContents(True)
		self.item_three_pic.setObjectName("item_three_pic")
		self.item_four_pic = QtWidgets.QLabel(self)
		self.item_four_pic.setGeometry(QtCore.QRect(670, 40, 71, 71))
		self.item_four_pic.setText("")
		self.item_four_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Filet O Fish.png"))
		self.item_four_pic.setScaledContents(True)
		self.item_four_pic.setObjectName("item_four_pic")
		self.item_four_text = QtWidgets.QLabel(self)
		self.item_four_text.setGeometry(QtCore.QRect(640, 110, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_four_text.setFont(font)
		self.item_four_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_four_text.setObjectName("item_four_text")
		self.item_one_price = QtWidgets.QLabel(self)
		self.item_one_price.setGeometry(QtCore.QRect(70, 130, 31, 16))
		self.item_one_price.setObjectName("item_one_price")
		self.item_two_text = QtWidgets.QLabel(self)
		self.item_two_text.setGeometry(QtCore.QRect(240, 110, 131, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_two_text.setFont(font)
		self.item_two_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_two_text.setObjectName("item_two_text")
		self.item_three_price = QtWidgets.QLabel(self)
		self.item_three_price.setGeometry(QtCore.QRect(480, 130, 31, 16))
		self.item_three_price.setObjectName("item_three_price")
		self.item_one_pic = QtWidgets.QLabel(self)
		self.item_one_pic.setGeometry(QtCore.QRect(50, 20, 100, 100))
		self.item_one_pic.setText("")
		self.item_one_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Double Mcspicy.png"))
		self.item_one_pic.setScaledContents(True)
		self.item_one_pic.setObjectName("item_one_pic")
		self.item_one_text = QtWidgets.QLabel(self)
		self.item_one_text.setGeometry(QtCore.QRect(40, 110, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_one_text.setFont(font)
		self.item_one_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_one_text.setObjectName("item_one_text")
		self.item_three_text = QtWidgets.QLabel(self)
		self.item_three_text.setGeometry(QtCore.QRect(420, 110, 171, 20))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_three_text.setFont(font)
		self.item_three_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_three_text.setObjectName("item_three_text")
		self.item_two_pic = QtWidgets.QLabel(self)
		self.item_two_pic.setGeometry(QtCore.QRect(259, 29, 91, 81))
		self.item_two_pic.setText("")
		self.item_two_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Big Mac.png"))
		self.item_two_pic.setScaledContents(True)
		self.item_two_pic.setObjectName("item_two_pic")
		self.item_four_price = QtWidgets.QLabel(self)
		self.item_four_price.setGeometry(QtCore.QRect(680, 130, 31, 16))
		self.item_four_price.setObjectName("item_four_price")
		self.item_ten_price = QtWidgets.QLabel(self)
		self.item_ten_price.setGeometry(QtCore.QRect(290, 480, 31, 16))
		self.item_ten_price.setObjectName("item_ten_price")
		self.item_nine_price = QtWidgets.QLabel(self)
		self.item_nine_price.setGeometry(QtCore.QRect(70, 480, 31, 16))
		self.item_nine_price.setObjectName("item_nine_price")
		self.item_ten_text = QtWidgets.QLabel(self)
		self.item_ten_text.setGeometry(QtCore.QRect(250, 460, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_ten_text.setFont(font)
		self.item_ten_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_ten_text.setObjectName("item_ten_text")
		self.item_nine_pic = QtWidgets.QLabel(self)
		self.item_nine_pic.setGeometry(QtCore.QRect(50, 370, 100, 100))
		self.item_nine_pic.setText("")
		self.item_nine_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Apple Pie.png"))
		self.item_nine_pic.setScaledContents(True)
		self.item_nine_pic.setObjectName("item_nine_pic")
		self.item_nine_text = QtWidgets.QLabel(self)
		self.item_nine_text.setGeometry(QtCore.QRect(40, 460, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_nine_text.setFont(font)
		self.item_nine_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_nine_text.setObjectName("item_nine_text")
		self.item_ten_pic = QtWidgets.QLabel(self)
		self.item_ten_pic.setGeometry(QtCore.QRect(270, 370, 71, 91))
		self.item_ten_pic.setText("")
		self.item_ten_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Fries.png"))
		self.item_ten_pic.setScaledContents(True)
		self.item_ten_pic.setObjectName("item_ten_pic")
		self.item_six_price.raise_()
		self.item_seven_pic.raise_()
		self.item_eight_pic.raise_()
		self.item_eight_text.raise_()
		self.item_five_price.raise_()
		self.item_six_text.raise_()
		self.item_seven_price.raise_()
		self.item_five_pic.raise_()
		self.item_five_text.raise_()
		self.item_seven_text.raise_()
		self.item_six_pic.raise_()
		self.item_eight_price.raise_()
		self.item_two_price.raise_()
		self.item_three_pic.raise_()
		self.item_four_pic.raise_()
		self.item_four_text.raise_()
		self.item_one_price.raise_()
		self.item_two_text.raise_()
		self.item_three_price.raise_()
		self.item_one_pic.raise_()
		self.item_one_text.raise_()
		self.item_three_text.raise_()
		self.item_two_pic.raise_()
		self.item_four_price.raise_()
		self.item_ten_price.raise_()
		self.item_nine_price.raise_()
		self.item_ten_text.raise_()
		self.item_nine_pic.raise_()
		self.item_nine_text.raise_()
		self.item_ten_pic.raise_()


		_translate = QtCore.QCoreApplication.translate
		self.setWindowTitle(_translate("Mcdonalds", "Form"))
		self.item_six_price.setText(_translate("Mcdonalds", "$5.7"))
		self.item_eight_text.setText(_translate("Mcdonalds", "Coke"))
		self.item_five_price.setText(_translate("Mcdonalds", "$4.2"))
		self.item_six_text.setText(_translate("Mcdonalds", "Mc Wrap"))
		self.item_seven_price.setText(_translate("Mcdonalds", "$3.2"))
		self.item_five_text.setText(_translate("Mcdonalds", "Mc Chicken"))
		self.item_seven_text.setText(_translate("Mcdonalds", "Mc Nugguts"))
		self.item_eight_price.setText(_translate("Mcdonalds", "$1.5"))
		self.item_two_price.setText(_translate("Mcdonalds", "$7.2"))
		self.item_four_text.setText(_translate("Mcdonalds", "Fliet O Fish"))
		self.item_one_price.setText(_translate("Mcdonalds", "$5.7"))
		self.item_two_text.setText(_translate("Mcdonalds", "Big Mac"))
		self.item_three_price.setText(_translate("Mcdonalds", "$4.3"))
		self.item_one_text.setText(_translate("Mcdonalds", "Double Mcspicy"))
		self.item_three_text.setText(_translate("Mcdonalds", "Double Cheese Burger"))
		self.item_four_price.setText(_translate("Mcdonalds", "$4.7"))
		self.item_ten_price.setText(_translate("Mcdonalds", "$1.6"))
		self.item_nine_price.setText(_translate("Mcdonalds", "$2.0"))
		self.item_ten_text.setText(_translate("Mcdonalds", "Fries"))
		self.item_nine_text.setText(_translate("Mcdonalds", "Apple Pie"))





	def setup_Ui_Am_Mcdonalds(self):
		self.setObjectName("Mcdonald")
		self.resize(800,600)

		self.setWindowOpacity(0.9)

		self.setAutoFillBackground(True)
		p = self.palette()
		p.setColor(self.backgroundRole(), QtCore.Qt.black)
		self.setPalette(p)
		self.gridLayout = QtWidgets.QGridLayout(self)
		self.gridLayout.setObjectName('gridLayout')
		self.operating_hour_text = QtWidgets.QLabel(self)
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.operating_hour_text.setFont(font)
		self.operating_hour_text.setAlignment(QtCore.Qt.AlignCenter)
		self.operating_hour_text.setGeometry(QtCore.QRect(460, 450, 300, 16))
		self.operating_hour_text.setObjectName("operating_hour_text")
		self.operating_hour_text.raise_()
		self.item_six_price = QtWidgets.QLabel(self)
		self.item_six_price.setGeometry(QtCore.QRect(280, 310, 31, 16))
		self.item_six_price.setObjectName("item_six_price")
		self.item_seven_pic = QtWidgets.QLabel(self)
		self.item_seven_pic.setGeometry(QtCore.QRect(450, 229, 100, 71))
		self.item_seven_pic.setText("")
		self.item_seven_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Apple Pie.png"))
		self.item_seven_pic.setScaledContents(True)
		self.item_seven_pic.setObjectName("item_seven_pic")
		self.item_eight_pic = QtWidgets.QLabel(self)
		self.item_eight_pic.setGeometry(QtCore.QRect(660, 219, 91, 81))
		self.item_eight_pic.setText("")
		self.item_eight_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Coffee.png"))
		self.item_eight_pic.setScaledContents(True)
		self.item_eight_pic.setObjectName("item_eight_pic")
		self.item_eight_text = QtWidgets.QLabel(self)
		self.item_eight_text.setGeometry(QtCore.QRect(650, 290, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_eight_text.setFont(font)
		self.item_eight_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_eight_text.setObjectName("item_eight_text")
		self.item_five_price = QtWidgets.QLabel(self)
		self.item_five_price.setGeometry(QtCore.QRect(70, 310, 31, 16))
		self.item_five_price.setObjectName("item_five_price")
		self.item_six_text = QtWidgets.QLabel(self)
		self.item_six_text.setGeometry(QtCore.QRect(250, 290, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_six_text.setFont(font)
		self.item_six_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_six_text.setObjectName("item_six_text")
		self.item_seven_price = QtWidgets.QLabel(self)
		self.item_seven_price.setGeometry(QtCore.QRect(480, 310, 31, 16))
		self.item_seven_price.setObjectName("item_seven_price")
		self.item_five_pic = QtWidgets.QLabel(self)
		self.item_five_pic.setGeometry(QtCore.QRect(50, 220, 91, 71))
		self.item_five_pic.setText("")
		self.item_five_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Filet O Fish.png"))
		self.item_five_pic.setScaledContents(True)
		self.item_five_pic.setObjectName("item_five_pic")
		self.item_five_text = QtWidgets.QLabel(self)
		self.item_five_text.setGeometry(QtCore.QRect(40, 290, 111, 20))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_five_text.setFont(font)
		self.item_five_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_five_text.setObjectName("item_five_text")
		self.item_seven_text = QtWidgets.QLabel(self)
		self.item_seven_text.setGeometry(QtCore.QRect(440, 290, 141, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_seven_text.setFont(font)
		self.item_seven_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_seven_text.setObjectName("item_seven_text")
		self.item_six_pic = QtWidgets.QLabel(self)
		self.item_six_pic.setGeometry(QtCore.QRect(260, 190, 100, 100))
		self.item_six_pic.setText("")
		self.item_six_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mcwings.png"))
		self.item_six_pic.setScaledContents(True)
		self.item_six_pic.setObjectName("item_six_pic")
		self.item_eight_price = QtWidgets.QLabel(self)
		self.item_eight_price.setGeometry(QtCore.QRect(690, 310, 31, 16))
		self.item_eight_price.setObjectName("item_eight_price")
		self.item_two_price = QtWidgets.QLabel(self)
		self.item_two_price.setGeometry(QtCore.QRect(280, 130, 31, 16))
		self.item_two_price.setObjectName("item_two_price")
		self.item_three_pic = QtWidgets.QLabel(self)
		self.item_three_pic.setGeometry(QtCore.QRect(450, 20, 100, 100))
		self.item_three_pic.setText("")
		self.item_three_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Hashbrown.png"))
		self.item_three_pic.setScaledContents(True)
		self.item_three_pic.setObjectName("item_three_pic")
		self.item_four_pic = QtWidgets.QLabel(self)
		self.item_four_pic.setGeometry(QtCore.QRect(670, 40, 71, 71))
		self.item_four_pic.setText("")
		self.item_four_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Corn Cup.png"))
		self.item_four_pic.setScaledContents(True)
		self.item_four_pic.setObjectName("item_four_pic")
		self.item_four_text = QtWidgets.QLabel(self)
		self.item_four_text.setGeometry(QtCore.QRect(640, 110, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_four_text.setFont(font)
		self.item_four_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_four_text.setObjectName("item_four_text")
		self.item_one_price = QtWidgets.QLabel(self)
		self.item_one_price.setGeometry(QtCore.QRect(70, 130, 31, 16))
		self.item_one_price.setObjectName("item_one_price")
		self.item_two_text = QtWidgets.QLabel(self)
		self.item_two_text.setGeometry(QtCore.QRect(240, 110, 131, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_two_text.setFont(font)
		self.item_two_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_two_text.setObjectName("item_two_text")
		self.item_three_price = QtWidgets.QLabel(self)
		self.item_three_price.setGeometry(QtCore.QRect(480, 130, 31, 16))
		self.item_three_price.setObjectName("item_three_price")
		self.item_one_pic = QtWidgets.QLabel(self)
		self.item_one_pic.setGeometry(QtCore.QRect(50, 20, 100, 100))
		self.item_one_pic.setText("")
		self.item_one_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Chicken Muffin.png"))
		self.item_one_pic.setScaledContents(True)
		self.item_one_pic.setObjectName("item_one_pic")
		self.item_one_text = QtWidgets.QLabel(self)
		self.item_one_text.setGeometry(QtCore.QRect(40, 110, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_one_text.setFont(font)
		self.item_one_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_one_text.setObjectName("item_one_text")
		self.item_three_text = QtWidgets.QLabel(self)
		self.item_three_text.setGeometry(QtCore.QRect(420, 110, 171, 20))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_three_text.setFont(font)
		self.item_three_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_three_text.setObjectName("item_three_text")
		self.item_two_pic = QtWidgets.QLabel(self)
		self.item_two_pic.setGeometry(QtCore.QRect(259, 29, 91, 81))
		self.item_two_pic.setText("")
		self.item_two_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Sausage Muffin.png"))
		self.item_two_pic.setScaledContents(True)
		self.item_two_pic.setObjectName("item_two_pic")
		self.item_four_price = QtWidgets.QLabel(self)
		self.item_four_price.setGeometry(QtCore.QRect(680, 130, 31, 16))
		self.item_four_price.setObjectName("item_four_price")
		self.item_ten_price = QtWidgets.QLabel(self)
		self.item_ten_price.setGeometry(QtCore.QRect(290, 480, 31, 16))
		self.item_ten_price.setObjectName("item_ten_price")
		self.item_nine_price = QtWidgets.QLabel(self)
		self.item_nine_price.setGeometry(QtCore.QRect(70, 480, 31, 16))
		self.item_nine_price.setObjectName("item_nine_price")
		self.item_ten_text = QtWidgets.QLabel(self)
		self.item_ten_text.setGeometry(QtCore.QRect(250, 460, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_ten_text.setFont(font)
		self.item_ten_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_ten_text.setObjectName("item_ten_text")
		self.item_nine_pic = QtWidgets.QLabel(self)
		self.item_nine_pic.setGeometry(QtCore.QRect(50, 370, 100, 100))
		self.item_nine_pic.setText("")
		self.item_nine_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Breakfast Platter.png"))
		self.item_nine_pic.setScaledContents(True)
		self.item_nine_pic.setObjectName("item_nine_pic")
		self.item_nine_text = QtWidgets.QLabel(self)
		self.item_nine_text.setGeometry(QtCore.QRect(40, 460, 121, 16))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.item_nine_text.setFont(font)
		self.item_nine_text.setAlignment(QtCore.Qt.AlignCenter)
		self.item_nine_text.setObjectName("item_nine_text")
		self.item_ten_pic = QtWidgets.QLabel(self)
		self.item_ten_pic.setGeometry(QtCore.QRect(270, 370, 71, 91))
		self.item_ten_pic.setText("")
		self.item_ten_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Fries.png"))
		self.item_ten_pic.setScaledContents(True)
		self.item_ten_pic.setObjectName("item_ten_pic")
		self.item_six_price.raise_()
		self.item_seven_pic.raise_()
		self.item_eight_pic.raise_()
		self.item_eight_text.raise_()
		self.item_five_price.raise_()
		self.item_six_text.raise_()
		self.item_seven_price.raise_()
		self.item_five_pic.raise_()
		self.item_five_text.raise_()
		self.item_seven_text.raise_()
		self.item_six_pic.raise_()
		self.item_eight_price.raise_()
		self.item_two_price.raise_()
		self.item_three_pic.raise_()
		self.item_four_pic.raise_()
		self.item_four_text.raise_()
		self.item_one_price.raise_()
		self.item_two_text.raise_()
		self.item_three_price.raise_()
		self.item_one_pic.raise_()
		self.item_one_text.raise_()
		self.item_three_text.raise_()
		self.item_two_pic.raise_()
		self.item_four_price.raise_()
		self.item_ten_price.raise_()
		self.item_nine_price.raise_()
		self.item_ten_text.raise_()
		self.item_nine_pic.raise_()
		self.item_nine_text.raise_()
		self.item_ten_pic.raise_()


		_translate = QtCore.QCoreApplication.translate
		self.setWindowTitle(_translate("Mcdonalds", "Form"))
		self.item_six_price.setText(_translate("Mcdonalds", "$3.5"))
		self.item_eight_text.setText(_translate("Mcdonalds", "Mc Coffee"))
		self.item_five_price.setText(_translate("Mcdonalds", "$5.2"))
		self.item_six_text.setText(_translate("Mcdonalds", "Mc Wings"))
		self.item_seven_price.setText(_translate("Mcdonalds", "$1.8"))
		self.item_five_text.setText(_translate("Mcdonalds", "Flit O Fish"))
		self.item_seven_text.setText(_translate("Mcdonalds", "Apple Pie"))
		self.item_eight_price.setText(_translate("Mcdonalds", "$1.5"))
		self.item_two_price.setText(_translate("Mcdonalds", "$3.2"))
		self.item_four_text.setText(_translate("Mcdonalds", "Corn Cup"))
		self.item_one_price.setText(_translate("Mcdonalds", "$3.5"))
		self.item_two_text.setText(_translate("Mcdonalds", "Sasuage Muffiin"))
		self.item_three_price.setText(_translate("Mcdonalds", "$1.8"))
		self.item_one_text.setText(_translate("Mcdonalds", "Chicken Muffin"))
		self.item_three_text.setText(_translate("Mcdonalds", "Hashbrown"))
		self.item_four_price.setText(_translate("Mcdonalds", "$4.7"))
		self.item_ten_price.setText(_translate("Mcdonalds", "$1.6"))
		self.item_nine_price.setText(_translate("Mcdonalds", "$8.2"))
		self.item_ten_text.setText(_translate("Mcdonalds", "Fries"))
		self.item_nine_text.setText(_translate("Mcdonalds", "Breakfast Platter"))
	

	def setupUi_MY(self,DateTimeDate):
		self.setObjectName('MalayStall')
		self.resize(800,600)


		self.setWindowOpacity(0.9)

		self.setAutoFillBackground(True)
		p = self.palette()
		p.setColor(self.backgroundRole(), QtCore.Qt.black)
		self.setPalette(p)
		self.gridLayout = QtWidgets.QGridLayout(self)
		self.gridLayout.setObjectName('gridLayout')


		MYMenuTuple = self.MYMenu(DateTimeDate)


		self.item0_price = QtWidgets.QLabel(self)
		self.item0_price.setGeometry(QtCore.QRect(80, 200, 31, 16))
		self.item0_price.setObjectName("item0_price")

		self.item1_price = QtWidgets.QLabel(self)
		self.item1_price.setGeometry(QtCore.QRect(330, 400, 31, 16))
		self.item1_price.setObjectName("item1_price")

		self.item2_price = QtWidgets.QLabel(self)
		self.item2_price.setGeometry(QtCore.QRect(80, 400, 31, 16))
		self.item2_price.setObjectName("item2_price")

		self.item3_price = QtWidgets.QLabel(self)
		self.item3_price.setGeometry(QtCore.QRect(330, 200, 31, 16))
		self.item3_price.setObjectName("item3_price")

		#self.MYBG = QtWidgets.QLabel(self)
		#self.MYBG.setGeometry(QtCore.QRect(4, -1, 701, 591))
		#self.MYBG.setObjectName("MYBG")

		self.item0_Pic = QtWidgets.QLabel(self)
		self.item0_Pic.setGeometry(QtCore.QRect(80, 90, 100, 71))
		self.item0_Pic.setObjectName("item0_Pic")

		self.item1_Pic = QtWidgets.QLabel(self)
		self.item1_Pic.setGeometry(QtCore.QRect(330, 310, 100, 71))
		self.item1_Pic.setObjectName("item1_Pic")

		self.item2_Pic = QtWidgets.QLabel(self)
		self.item2_Pic.setGeometry(QtCore.QRect(80, 310, 100, 71))
		self.item2_Pic.setObjectName("item2_Pic")

		self.item3_Pic = QtWidgets.QLabel(self)
		self.item3_Pic.setGeometry(QtCore.QRect(330, 90, 100, 71))
		self.item3_Pic.setObjectName("item3_Pic")
	
		self.item0_Name = QtWidgets.QLabel(self)
		self.item0_Name.setGeometry(QtCore.QRect(80, 180, 61, 16))
		self.item0_Name.setObjectName("item0_Name")

		self.item1_Name = QtWidgets.QLabel(self)
		self.item1_Name.setGeometry(QtCore.QRect(330, 420, 51, 16))
		self.item1_Name.setObjectName("item1_Name")

		self.item2_Name = QtWidgets.QLabel(self)
		self.item2_Name.setGeometry(QtCore.QRect(80, 420, 61, 16))
		self.item2_Name.setObjectName("item2_Name")

		self.item3_Name = QtWidgets.QLabel(self)
		self.item3_Name.setGeometry(QtCore.QRect(330, 180, 61, 16))
		self.item3_Name.setObjectName("item3_Name")

		#self.MYBG.raise_()
		self.item0_price.raise_()
		self.item1_price.raise_()
		self.item2_price.raise_()
		self.item3_price.raise_()
		self.item0_Pic.raise_()
		self.item1_Pic.raise_()
		self.item2_Pic.raise_()
		self.item3_Pic.raise_()
		self.item0_Name.raise_()
		self.item1_Name.raise_()
		self.item2_Name.raise_()
		self.item3_Name.raise_()

		
		self.retranslateUi_MY(MYMenuTuple)


	def setupUi_Subway(self,DatetimeTime):
		self.setObjectName("Subway")
		self.resize(800, 600)

		self.setWindowOpacity(0.9)

		self.setAutoFillBackground(True)
		p = self.palette()
		p.setColor(self.backgroundRole(), QtCore.Qt.black)
		self.setPalette(p)
		self.gridLayout = QtWidgets.QGridLayout(self)
		self.gridLayout.setObjectName('gridLayout')

		#page 1 Subway
		SubwayMenuTuple = self.SubwayMenu(DatetimeTime)
   
		self.Item0Price = QtWidgets.QLabel(self)
		self.Item0Price.setGeometry(QtCore.QRect(80, 200, 31, 16))
		self.Item0Price.setObjectName("Item0Price")
		self.Item1Price = QtWidgets.QLabel(self)
		self.Item1Price.setGeometry(QtCore.QRect(380, 200, 31, 16))
		self.Item1Price.setObjectName("Item1Price")
		self.Item2Price = QtWidgets.QLabel(self)
		self.Item2Price.setGeometry(QtCore.QRect(80, 400, 31, 16))
		self.Item2Price.setObjectName("Item2Price")
		self.Item3Price = QtWidgets.QLabel(self)
		self.Item3Price.setGeometry(QtCore.QRect(330, 400, 31, 16))
		self.Item3Price.setObjectName("Item3Price")

		self.SubwayBG = QtWidgets.QLabel(self)
		self.SubwayBG.setGeometry(QtCore.QRect(20, 0, 708, 588))
		self.SubwayBG.setObjectName("SubwayBG")
		self.Item0Pic = QtWidgets.QLabel(self)
		self.Item0Pic.setGeometry(QtCore.QRect(80, 90, 100, 71))
		self.Item0Pic.setObjectName("Item0Pic")
		self.Item1Pic = QtWidgets.QLabel(self)
		self.Item1Pic.setGeometry(QtCore.QRect(380, 100, 100, 71))
		self.Item1Pic.setObjectName("Item1Pic")
		self.Item2Pic = QtWidgets.QLabel(self)
		self.Item2Pic.setGeometry(QtCore.QRect(70, 320, 100, 71))
		self.Item2Pic.setObjectName("Item2Pic")
		self.Item3Pic = QtWidgets.QLabel(self)
		self.Item3Pic.setGeometry(QtCore.QRect(330, 310, 100, 71))
		self.Item3Pic.setObjectName("Item3Pic")
		
		
		self.Item0Name = QtWidgets.QLabel(self)
		self.Item0Name.setGeometry(QtCore.QRect(80, 180, 121, 16))
		self.Item0Name.setObjectName("Item0Name")
		self.Item1Name = QtWidgets.QLabel(self)
		self.Item1Name.setGeometry(QtCore.QRect(380, 180, 121, 16))
		self.Item1Name.setObjectName("Item1Name")
		self.Item2Name = QtWidgets.QLabel(self)
		self.Item2Name.setGeometry(QtCore.QRect(80, 420, 121, 16))
		self.Item2Name.setObjectName("Item2Name")
		self.Item3Name = QtWidgets.QLabel(self)
		self.Item3Name.setGeometry(QtCore.QRect(330, 420, 121, 16))
		self.Item3Name.setObjectName("Item3Name")
		self.label_4 = QtWidgets.QLabel(self)
		self.label_4.setGeometry(QtCore.QRect(-86, -1, 131, 141))
		self.label_4.setObjectName("label_4")
		
		self.SubwayBG.raise_()


		self.Item0Price.raise_()
		self.Item1Price.raise_()
		self.Item2Price.raise_()
		self.Item3Price.raise_()
		self.Item0Pic.raise_()
		self.Item1Pic.raise_()
		self.Item2Pic.raise_()
		self.Item3Pic.raise_()

		self.Item0Name.raise_()
		self.Item1Name.raise_()
		self.Item2Name.raise_()
		self.Item3Name.raise_()
		self.label_4.raise_()

		

		self.retranslateUi_Sub(SubwayMenuTuple)
		
		QtCore.QMetaObject.connectSlotsByName(self)
	
	
	
	def retranslateUi_Sub(self,SubwayMenuTuple):
		_translate = QtCore.QCoreApplication.translate
		self.setWindowTitle(_translate("Subway", "Subway"))

		self.Item0Price.setText(_translate("Subway", SubwayMenuTuple[0][1]))
		self.Item1Price.setText(_translate("Subway", SubwayMenuTuple[1][1]))
		self.Item2Price.setText(_translate("Subway", SubwayMenuTuple[2][1]))
		self.Item3Price.setText(_translate("Subway", SubwayMenuTuple[3][1]))
		self.SubwayBG.setText(_translate("Subway", "Subway"))
		self.Item0Pic.setText(_translate("Subway", "Item0Pic"))
		self.Item1Pic.setText(_translate("Subway", "Item1Pic"))
		self.Item2Pic.setText(_translate("Subway", "Item2Pic"))
		self.Item3Pic.setText(_translate("Subway", "Item3Pic"))
		

		self.Item0Name.setText(_translate("Subway", SubwayMenuTuple[0][0]))
		self.Item1Name.setText(_translate("Subway", SubwayMenuTuple[1][0]))
		self.Item2Name.setText(_translate("Subway", SubwayMenuTuple[2][0]))
		self.Item3Name.setText(_translate("Subway", SubwayMenuTuple[3][0]))
		self.label_4.setText(_translate("Subway", "TextLabel"))

	def retranslateUi_MY(self,MYMenuTuple):
		_translate = QtCore.QCoreApplication.translate
		self.setWindowTitle(_translate("MalayStall", "Malay Stall"))

		self.item0_price.setText(_translate("MalayStall", MYMenuTuple[0][1]))
		self.item1_price.setText(_translate("MalayStall", MYMenuTuple[1][1]))
		self.item2_price.setText(_translate("MalayStall", MYMenuTuple[2][1]))
		self.item3_price.setText(_translate("MalayStall", MYMenuTuple[3][1]))
		#self.MYBG.setText(_translate("MalayStall", "MY Stall"))
		self.item0_Pic.setText(_translate("MalayStall", "item0_Pic"))
		self.item1_Pic.setText(_translate("MalayStall", "item1_Pic"))
		self.item2_Pic.setText(_translate("MalayStall", "item2_Pic"))
		self.item3_Pic.setText(_translate("MalayStall", "item3_Pic"))

		self.item0_Name.setText(_translate("MalayStall", MYMenuTuple[0][0]))
		self.item1_Name.setText(_translate("MalayStall", MYMenuTuple[1][0]))
		self.item2_Name.setText(_translate("MalayStall", MYMenuTuple[2][0]))
		self.item3_Name.setText(_translate("MalayStall", MYMenuTuple[3][0]))
		#self.OpTime.setText(_translate('Subway','12AM-12PM'))
		#self.OkButton.setText(_translate("Subway",'Ok'))

		
	
	def SubwayMenu(self,SelectedTime):
		BreakfastTuple = ('Egg & Cheese','S$6.8'),('Chicken Bacon','S$7.5'),('Chicken Ham','S$5.6'),('Chicken Sausage','S$6.9')
		LunchTuple = ('Chicken Tariyaki','S$7.9'),('Roast Beef','S$10.5'),('Egg Mayo','S$5.6'),('Veggie Delite','S$5.9')
		if SelectedTime < 11:
			MenuTuple = BreakfastTuple
		else:
			MenuTuple = LunchTuple
		return MenuTuple
	def MYMenu(self,SelectedDate):
		EvenDayMenuTuple = ('Laksa','S$5'),('Nasi Lemak','S$6'),('Nasi Briyani','S$6'),('Mee Soto','S$5.5')
		OddDayMenuTuple = ('Nasi Kerabu','S$5.5'),('Nasi Kandar','S$5.5'),('Rojak','S$4'),('Mee Goreng Mamak','S$6.5')
		#Date = current_time.weekday() + 1
		if SelectedDate % 2 == 0:
			print('Even days menu')
			MenuTuple = EvenDayMenuTuple
		else:
			print('Odd days menu')
			MenuTuple = OddDayMenuTuple
		return MenuTuple 




