from PyQt5.QtGui import QPixmap, QPainter
from PyQt5.QtWidgets import QWidget ,QMessageBox,QApplication,QStackedWidget ,QVBoxLayout,QHBoxLayout,QListWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, pyqtSignal, QTimer,QDate, QTime
import os
from datetime import datetime
import pytz
import kfcCombine


class ViewMenus_MacC(QWidget):

    #menu from the McDonalds.py where we remove all the counters and buttons
    def setup_Ui_Pm_Mcdonalds(self):
        self.setObjectName("Pm Mcdonald")
        self.resize(800,600)
      #set a stall background
        self.McBackpic2 = QtWidgets.QLabel(self)
        self.McBackpic2.setText("")
        self.McBackpic2.setPixmap(QtGui.QPixmap("./Pictures/kfc/Mcbackground_1.jpg"))
        self.McBackpic2.setScaledContents(True)
        self.McBackpic2.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.McBackpic2.setObjectName("McBackpic")
        
        self.operating_hour_text = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
  

        self.operating_hour_text.setFont(font)
        self.operating_hour_text.setAlignment(QtCore.Qt.AlignCenter)
        self.operating_hour_text.setGeometry(QtCore.QRect(460, 450, 300, 16))
        self.operating_hour_text.setObjectName("operating_hour_text")
        self.operating_hour_text.raise_()
        self.item_six_price = QtWidgets.QLabel(self)
        self.item_six_price.setGeometry(QtCore.QRect(280, 310, 31, 16))
        self.item_six_price.setObjectName("item_six_price")
        self.item_seven_pic = QtWidgets.QLabel(self)
        self.item_seven_pic.setGeometry(QtCore.QRect(450, 229, 100, 71))
        self.item_seven_pic.setText("")
        self.item_seven_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Nugguts.png"))
        self.item_seven_pic.setScaledContents(True)
        self.item_seven_pic.setObjectName("item_seven_pic")
        self.item_eight_pic = QtWidgets.QLabel(self)
        self.item_eight_pic.setGeometry(QtCore.QRect(660, 219, 91, 81))
        self.item_eight_pic.setText("")
        self.item_eight_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Coke.png"))
        self.item_eight_pic.setScaledContents(True)
        self.item_eight_pic.setObjectName("item_eight_pic")
        self.item_eight_text = QtWidgets.QLabel(self)
        self.item_eight_text.setGeometry(QtCore.QRect(650, 290, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_eight_text.setFont(font)
        self.item_eight_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_eight_text.setObjectName("item_eight_text")
        self.item_five_price = QtWidgets.QLabel(self)
        self.item_five_price.setGeometry(QtCore.QRect(70, 310, 31, 16))
        self.item_five_price.setObjectName("item_five_price")
        self.item_six_text = QtWidgets.QLabel(self)
        self.item_six_text.setGeometry(QtCore.QRect(250, 290, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_six_text.setFont(font)
        self.item_six_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_six_text.setObjectName("item_six_text")
        self.item_seven_price = QtWidgets.QLabel(self)
        self.item_seven_price.setGeometry(QtCore.QRect(480, 310, 31, 16))
        self.item_seven_price.setObjectName("item_seven_price")
        self.item_five_pic = QtWidgets.QLabel(self)
        self.item_five_pic.setGeometry(QtCore.QRect(50, 220, 91, 71))
        self.item_five_pic.setText("")
        self.item_five_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Chicken.png"))
        self.item_five_pic.setScaledContents(True)
        self.item_five_pic.setObjectName("item_five_pic")
        self.item_five_text = QtWidgets.QLabel(self)
        self.item_five_text.setGeometry(QtCore.QRect(40, 290, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_five_text.setFont(font)
        self.item_five_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_five_text.setObjectName("item_five_text")
        self.item_seven_text = QtWidgets.QLabel(self)
        self.item_seven_text.setGeometry(QtCore.QRect(440, 290, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_seven_text.setFont(font)
        self.item_seven_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_seven_text.setObjectName("item_seven_text")
        self.item_six_pic = QtWidgets.QLabel(self)
        self.item_six_pic.setGeometry(QtCore.QRect(260, 190, 100, 100))
        self.item_six_pic.setText("")
        self.item_six_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Wrap.png"))
        self.item_six_pic.setScaledContents(True)
        self.item_six_pic.setObjectName("item_six_pic")
        self.item_eight_price = QtWidgets.QLabel(self)
        self.item_eight_price.setGeometry(QtCore.QRect(690, 310, 31, 16))
        self.item_eight_price.setObjectName("item_eight_price")
        self.item_two_price = QtWidgets.QLabel(self)
        self.item_two_price.setGeometry(QtCore.QRect(280, 130, 31, 16))
        self.item_two_price.setObjectName("item_two_price")
        self.item_three_pic = QtWidgets.QLabel(self)
        self.item_three_pic.setGeometry(QtCore.QRect(450, 20, 100, 100))
        self.item_three_pic.setText("")
        self.item_three_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Double Cheese Burger.png"))
        self.item_three_pic.setScaledContents(True)
        self.item_three_pic.setObjectName("item_three_pic")
        self.item_four_pic = QtWidgets.QLabel(self)
        self.item_four_pic.setGeometry(QtCore.QRect(670, 40, 71, 71))
        self.item_four_pic.setText("")
        self.item_four_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Filet O Fish.png"))
        self.item_four_pic.setScaledContents(True)
        self.item_four_pic.setObjectName("item_four_pic")
        self.item_four_text = QtWidgets.QLabel(self)
        self.item_four_text.setGeometry(QtCore.QRect(640, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_four_text.setFont(font)
        self.item_four_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_four_text.setObjectName("item_four_text")
        self.item_one_price = QtWidgets.QLabel(self)
        self.item_one_price.setGeometry(QtCore.QRect(70, 130, 31, 16))
        self.item_one_price.setObjectName("item_one_price")
        self.item_two_text = QtWidgets.QLabel(self)
        self.item_two_text.setGeometry(QtCore.QRect(240, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_two_text.setFont(font)
        self.item_two_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_two_text.setObjectName("item_two_text")
        self.item_three_price = QtWidgets.QLabel(self)
        self.item_three_price.setGeometry(QtCore.QRect(480, 130, 31, 16))
        self.item_three_price.setObjectName("item_three_price")
        self.item_one_pic = QtWidgets.QLabel(self)
        self.item_one_pic.setGeometry(QtCore.QRect(50, 20, 100, 100))
        self.item_one_pic.setText("")
        self.item_one_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Double Mcspicy.png"))
        self.item_one_pic.setScaledContents(True)
        self.item_one_pic.setObjectName("item_one_pic")
        self.item_one_text = QtWidgets.QLabel(self)
        self.item_one_text.setGeometry(QtCore.QRect(40, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_one_text.setFont(font)
        self.item_one_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_one_text.setObjectName("item_one_text")
        self.item_three_text = QtWidgets.QLabel(self)
        self.item_three_text.setGeometry(QtCore.QRect(420, 110, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_three_text.setFont(font)
        self.item_three_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_three_text.setObjectName("item_three_text")
        self.item_two_pic = QtWidgets.QLabel(self)
        self.item_two_pic.setGeometry(QtCore.QRect(259, 29, 91, 81))
        self.item_two_pic.setText("")
        self.item_two_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Big Mac.png"))
        self.item_two_pic.setScaledContents(True)
        self.item_two_pic.setObjectName("item_two_pic")
        self.item_four_price = QtWidgets.QLabel(self)
        self.item_four_price.setGeometry(QtCore.QRect(680, 130, 31, 16))
        self.item_four_price.setObjectName("item_four_price")
        self.item_ten_price = QtWidgets.QLabel(self)
        self.item_ten_price.setGeometry(QtCore.QRect(290, 480, 31, 16))
        self.item_ten_price.setObjectName("item_ten_price")
        self.item_nine_price = QtWidgets.QLabel(self)
        self.item_nine_price.setGeometry(QtCore.QRect(70, 480, 31, 16))
        self.item_nine_price.setObjectName("item_nine_price")
        self.item_ten_text = QtWidgets.QLabel(self)
        self.item_ten_text.setGeometry(QtCore.QRect(250, 460, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_ten_text.setFont(font)
        self.item_ten_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_ten_text.setObjectName("item_ten_text")
        self.item_nine_pic = QtWidgets.QLabel(self)
        self.item_nine_pic.setGeometry(QtCore.QRect(50, 370, 100, 100))
        self.item_nine_pic.setText("")
        self.item_nine_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Apple Pie.png"))
        self.item_nine_pic.setScaledContents(True)
        self.item_nine_pic.setObjectName("item_nine_pic")
        self.item_nine_text = QtWidgets.QLabel(self)
        self.item_nine_text.setGeometry(QtCore.QRect(40, 460, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_nine_text.setFont(font)
        self.item_nine_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_nine_text.setObjectName("item_nine_text")
        self.item_ten_pic = QtWidgets.QLabel(self)
        self.item_ten_pic.setGeometry(QtCore.QRect(270, 370, 71, 91))
        self.item_ten_pic.setText("")
        self.item_ten_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Fries.png"))
        self.item_ten_pic.setScaledContents(True)
        self.item_ten_pic.setObjectName("item_ten_pic")
        self.item_six_price.raise_()
        self.item_seven_pic.raise_()
        self.item_eight_pic.raise_()
        self.item_eight_text.raise_()
        self.item_five_price.raise_()
        self.item_six_text.raise_()
        self.item_seven_price.raise_()
        self.item_five_pic.raise_()
        self.item_five_text.raise_()
        self.item_seven_text.raise_()
        self.item_six_pic.raise_()
        self.item_eight_price.raise_()
        self.item_two_price.raise_()
        self.item_three_pic.raise_()
        self.item_four_pic.raise_()
        self.item_four_text.raise_()
        self.item_one_price.raise_()
        self.item_two_text.raise_()
        self.item_three_price.raise_()
        self.item_one_pic.raise_()
        self.item_one_text.raise_()
        self.item_three_text.raise_()
        self.item_two_pic.raise_()
        self.item_four_price.raise_()
        self.item_ten_price.raise_()
        self.item_nine_price.raise_()
        self.item_ten_text.raise_()
        self.item_nine_pic.raise_()
        self.item_nine_text.raise_()
        self.item_ten_pic.raise_()
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Mcdonalds", "Form"))
        self.item_six_price.setText(_translate("Mcdonalds", "$5.7"))
        self.item_eight_text.setText(_translate("Mcdonalds", "Coke"))
        self.item_five_price.setText(_translate("Mcdonalds", "$4.2"))
        self.item_six_text.setText(_translate("Mcdonalds", "Mc Wrap"))
        self.item_seven_price.setText(_translate("Mcdonalds", "$3.2"))
        self.item_five_text.setText(_translate("Mcdonalds", "Mc Chicken"))
        self.item_seven_text.setText(_translate("Mcdonalds", "Mc Nugguts"))
        self.item_eight_price.setText(_translate("Mcdonalds", "$1.5"))
        self.item_two_price.setText(_translate("Mcdonalds", "$7.2"))
        self.item_four_text.setText(_translate("Mcdonalds", "Fliet O Fish"))
        self.item_one_price.setText(_translate("Mcdonalds", "$5.7"))
        self.item_two_text.setText(_translate("Mcdonalds", "Big Mac"))
        self.item_three_price.setText(_translate("Mcdonalds", "$4.3"))
        self.item_one_text.setText(_translate("Mcdonalds", "Double Mcspicy"))
        self.item_three_text.setText(_translate("Mcdonalds", "Double Cheese Burger"))
        self.item_four_price.setText(_translate("Mcdonalds", "$4.7"))
        self.item_ten_price.setText(_translate("Mcdonalds", "$1.6"))
        self.item_nine_price.setText(_translate("Mcdonalds", "$2.0"))
        self.item_ten_text.setText(_translate("Mcdonalds", "Fries"))
        self.item_nine_text.setText(_translate("Mcdonalds", "Apple Pie"))


    def setup_Ui_Am_Mcdonalds(self):
        self.setObjectName("Mcdonald")
        self.resize(800,600)

      #set a stall background
        self.McBackpic1 = QtWidgets.QLabel(self)
        self.McBackpic1.setText("")
        self.McBackpic1.setPixmap(QtGui.QPixmap("./Pictures/kfc/Mcbackground_1.jpg"))
        self.McBackpic1.setScaledContents(True)
        self.McBackpic1.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.McBackpic1.setObjectName("McBackpic")

        self.operating_hour_text = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)


        self.operating_hour_text.setFont(font)
        self.operating_hour_text.setAlignment(QtCore.Qt.AlignCenter)
        self.operating_hour_text.setGeometry(QtCore.QRect(460, 450, 300, 16))
        self.operating_hour_text.setObjectName("operating_hour_text")
        self.operating_hour_text.raise_()
        self.item_six_price = QtWidgets.QLabel(self)
        self.item_six_price.setGeometry(QtCore.QRect(280, 310, 31, 16))
        self.item_six_price.setObjectName("item_six_price")
        self.item_seven_pic = QtWidgets.QLabel(self)
        self.item_seven_pic.setGeometry(QtCore.QRect(450, 229, 100, 71))
        self.item_seven_pic.setText("")
        self.item_seven_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Apple Pie.png"))
        self.item_seven_pic.setScaledContents(True)
        self.item_seven_pic.setObjectName("item_seven_pic")
        self.item_eight_pic = QtWidgets.QLabel(self)
        self.item_eight_pic.setGeometry(QtCore.QRect(660, 219, 91, 81))
        self.item_eight_pic.setText("")
        self.item_eight_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Coffee.png"))
        self.item_eight_pic.setScaledContents(True)
        self.item_eight_pic.setObjectName("item_eight_pic")
        self.item_eight_text = QtWidgets.QLabel(self)
        self.item_eight_text.setGeometry(QtCore.QRect(650, 290, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_eight_text.setFont(font)
        self.item_eight_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_eight_text.setObjectName("item_eight_text")
        self.item_five_price = QtWidgets.QLabel(self)
        self.item_five_price.setGeometry(QtCore.QRect(70, 310, 31, 16))
        self.item_five_price.setObjectName("item_five_price")
        self.item_six_text = QtWidgets.QLabel(self)
        self.item_six_text.setGeometry(QtCore.QRect(250, 290, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_six_text.setFont(font)
        self.item_six_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_six_text.setObjectName("item_six_text")
        self.item_seven_price = QtWidgets.QLabel(self)
        self.item_seven_price.setGeometry(QtCore.QRect(480, 310, 31, 16))
        self.item_seven_price.setObjectName("item_seven_price")
        self.item_five_pic = QtWidgets.QLabel(self)
        self.item_five_pic.setGeometry(QtCore.QRect(50, 220, 91, 71))
        self.item_five_pic.setText("")
        self.item_five_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Filet O Fish.png"))
        self.item_five_pic.setScaledContents(True)
        self.item_five_pic.setObjectName("item_five_pic")
        self.item_five_text = QtWidgets.QLabel(self)
        self.item_five_text.setGeometry(QtCore.QRect(40, 290, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_five_text.setFont(font)
        self.item_five_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_five_text.setObjectName("item_five_text")
        self.item_seven_text = QtWidgets.QLabel(self)
        self.item_seven_text.setGeometry(QtCore.QRect(440, 290, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_seven_text.setFont(font)
        self.item_seven_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_seven_text.setObjectName("item_seven_text")
        self.item_six_pic = QtWidgets.QLabel(self)
        self.item_six_pic.setGeometry(QtCore.QRect(260, 190, 100, 100))
        self.item_six_pic.setText("")
        self.item_six_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mcwings.png"))
        self.item_six_pic.setScaledContents(True)
        self.item_six_pic.setObjectName("item_six_pic")
        self.item_eight_price = QtWidgets.QLabel(self)
        self.item_eight_price.setGeometry(QtCore.QRect(690, 310, 31, 16))
        self.item_eight_price.setObjectName("item_eight_price")
        self.item_two_price = QtWidgets.QLabel(self)
        self.item_two_price.setGeometry(QtCore.QRect(280, 130, 31, 16))
        self.item_two_price.setObjectName("item_two_price")
        self.item_three_pic = QtWidgets.QLabel(self)
        self.item_three_pic.setGeometry(QtCore.QRect(450, 20, 100, 100))
        self.item_three_pic.setText("")
        self.item_three_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Hashbrown.png"))
        self.item_three_pic.setScaledContents(True)
        self.item_three_pic.setObjectName("item_three_pic")
        self.item_four_pic = QtWidgets.QLabel(self)
        self.item_four_pic.setGeometry(QtCore.QRect(670, 40, 71, 71))
        self.item_four_pic.setText("")
        self.item_four_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Corn Cup.png"))
        self.item_four_pic.setScaledContents(True)
        self.item_four_pic.setObjectName("item_four_pic")
        self.item_four_text = QtWidgets.QLabel(self)
        self.item_four_text.setGeometry(QtCore.QRect(640, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_four_text.setFont(font)
        self.item_four_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_four_text.setObjectName("item_four_text")
        self.item_one_price = QtWidgets.QLabel(self)
        self.item_one_price.setGeometry(QtCore.QRect(70, 130, 31, 16))
        self.item_one_price.setObjectName("item_one_price")
        self.item_two_text = QtWidgets.QLabel(self)
        self.item_two_text.setGeometry(QtCore.QRect(240, 110, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_two_text.setFont(font)
        self.item_two_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_two_text.setObjectName("item_two_text")
        self.item_three_price = QtWidgets.QLabel(self)
        self.item_three_price.setGeometry(QtCore.QRect(480, 130, 31, 16))
        self.item_three_price.setObjectName("item_three_price")
        self.item_one_pic = QtWidgets.QLabel(self)
        self.item_one_pic.setGeometry(QtCore.QRect(50, 20, 100, 100))
        self.item_one_pic.setText("")
        self.item_one_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Chicken Muffin.png"))
        self.item_one_pic.setScaledContents(True)
        self.item_one_pic.setObjectName("item_one_pic")
        self.item_one_text = QtWidgets.QLabel(self)
        self.item_one_text.setGeometry(QtCore.QRect(40, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_one_text.setFont(font)
        self.item_one_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_one_text.setObjectName("item_one_text")
        self.item_three_text = QtWidgets.QLabel(self)
        self.item_three_text.setGeometry(QtCore.QRect(420, 110, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_three_text.setFont(font)
        self.item_three_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_three_text.setObjectName("item_three_text")
        self.item_two_pic = QtWidgets.QLabel(self)
        self.item_two_pic.setGeometry(QtCore.QRect(259, 29, 91, 81))
        self.item_two_pic.setText("")
        self.item_two_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Mc Sausage Muffin.png"))
        self.item_two_pic.setScaledContents(True)
        self.item_two_pic.setObjectName("item_two_pic")
        self.item_four_price = QtWidgets.QLabel(self)
        self.item_four_price.setGeometry(QtCore.QRect(680, 130, 31, 16))
        self.item_four_price.setObjectName("item_four_price")
        self.item_ten_price = QtWidgets.QLabel(self)
        self.item_ten_price.setGeometry(QtCore.QRect(290, 480, 31, 16))
        self.item_ten_price.setObjectName("item_ten_price")
        self.item_nine_price = QtWidgets.QLabel(self)
        self.item_nine_price.setGeometry(QtCore.QRect(70, 480, 31, 16))
        self.item_nine_price.setObjectName("item_nine_price")
        self.item_ten_text = QtWidgets.QLabel(self)
        self.item_ten_text.setGeometry(QtCore.QRect(250, 460, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_ten_text.setFont(font)
        self.item_ten_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_ten_text.setObjectName("item_ten_text")
        self.item_nine_pic = QtWidgets.QLabel(self)
        self.item_nine_pic.setGeometry(QtCore.QRect(50, 370, 100, 100))
        self.item_nine_pic.setText("")
        self.item_nine_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Breakfast Platter.png"))
        self.item_nine_pic.setScaledContents(True)
        self.item_nine_pic.setObjectName("item_nine_pic")
        self.item_nine_text = QtWidgets.QLabel(self)
        self.item_nine_text.setGeometry(QtCore.QRect(40, 460, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.item_nine_text.setFont(font)
        self.item_nine_text.setAlignment(QtCore.Qt.AlignCenter)
        self.item_nine_text.setObjectName("item_nine_text")
        self.item_ten_pic = QtWidgets.QLabel(self)
        self.item_ten_pic.setGeometry(QtCore.QRect(270, 370, 71, 91))
        self.item_ten_pic.setText("")
        self.item_ten_pic.setPixmap(QtGui.QPixmap("./Pictures/McDonalds/Fries.png"))
        self.item_ten_pic.setScaledContents(True)
        self.item_ten_pic.setObjectName("item_ten_pic")
        self.item_six_price.raise_()
        self.item_seven_pic.raise_()
        self.item_eight_pic.raise_()
        self.item_eight_text.raise_()
        self.item_five_price.raise_()
        self.item_six_text.raise_()
        self.item_seven_price.raise_()
        self.item_five_pic.raise_()
        self.item_five_text.raise_()
        self.item_seven_text.raise_()
        self.item_six_pic.raise_()
        self.item_eight_price.raise_()
        self.item_two_price.raise_()
        self.item_three_pic.raise_()
        self.item_four_pic.raise_()
        self.item_four_text.raise_()
        self.item_one_price.raise_()
        self.item_two_text.raise_()
        self.item_three_price.raise_()
        self.item_one_pic.raise_()
        self.item_one_text.raise_()
        self.item_three_text.raise_()
        self.item_two_pic.raise_()
        self.item_four_price.raise_()
        self.item_ten_price.raise_()
        self.item_nine_price.raise_()
        self.item_ten_text.raise_()
        self.item_nine_pic.raise_()
        self.item_nine_text.raise_()
        self.item_ten_pic.raise_()
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Mcdonalds", "Form"))
        self.item_six_price.setText(_translate("Mcdonalds", "$3.5"))
        self.item_eight_text.setText(_translate("Mcdonalds", "Mc Coffee"))
        self.item_five_price.setText(_translate("Mcdonalds", "$5.2"))
        self.item_six_text.setText(_translate("Mcdonalds", "Mc Wings"))
        self.item_seven_price.setText(_translate("Mcdonalds", "$1.8"))
        self.item_five_text.setText(_translate("Mcdonalds", "Flit O Fish"))
        self.item_seven_text.setText(_translate("Mcdonalds", "Apple Pie"))
        self.item_eight_price.setText(_translate("Mcdonalds", "$1.5"))
        self.item_two_price.setText(_translate("Mcdonalds", "$3.2"))
        self.item_four_text.setText(_translate("Mcdonalds", "Corn Cup"))
        self.item_one_price.setText(_translate("Mcdonalds", "$3.5"))
        self.item_two_text.setText(_translate("Mcdonalds", "Sasuage Muffiin"))
        self.item_three_price.setText(_translate("Mcdonalds", "$1.8"))
        self.item_one_text.setText(_translate("Mcdonalds", "Chicken Muffin"))
        self.item_three_text.setText(_translate("Mcdonalds", "Hashbrown"))
        self.item_four_price.setText(_translate("Mcdonalds", "$4.7"))
        self.item_ten_price.setText(_translate("Mcdonalds", "$1.6"))
        self.item_nine_price.setText(_translate("Mcdonalds", "$8.2"))
        self.item_ten_text.setText(_translate("Mcdonalds", "Fries"))
        self.item_nine_text.setText(_translate("Mcdonalds", "Breakfast Platter"))
        
